"use client";
import Link, {useAppLocation,resolvePath} from "./navigation";

import {createContext,useContext,useEffect,useState,useRef, type ReactNode} from "react";
import {ArrowRight,ArrowUpRight,Search,Menu,X,MapPin,Camera as Instagram,MessageCircle as Facebook,Play,Pause,Bookmark,BookOpen,Heart,Headphones,Users,ChevronRight,Check,Radio,ExternalLink,Volume2} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import data from "./content.json";
import additional from "./additional-pages.json";
import ClientBoundary from "./client-boundary";
export const D:any=data;
export const allItems=[...D.projects.map((x:any)=>({...x,kind:"Project"})),...D.programmes.map((x:any)=>({...x,kind:"Programme"})),...D.resources.map((x:any)=>({...x,kind:"Media"})),...D.devotionals.map((x:any)=>({...x,kind:"Devotional"})),...D.branches.map((x:any)=>({...x,title:x.name,href:x.href,kind:"Branch"})),...D.episodes.map((x:any)=>({...x,kind:"Podcast"})),...additional.map((x:any)=>({...x,href:x.slug==="family-games"?"/archive/family-games":"/"+x.slug,kind:x.isHistorical?"Archive":"Community"})),...[{slug:"about",title:"Our story & values"},{slug:"leadership",title:"Leadership"},{slug:"ministries",title:"Ministries"},{slug:"stories",title:"My CYI stories"},{slug:"gallery",title:"Photo journal"},{slug:"explore",title:"Explore all CYI pages"},{slug:"connect",title:"Get connected"}].map(x=>({...x,href:"/"+x.slug,kind:"Page"}))];
export type SavedItem={key:string;title:string;href:string;kind:string};
type AppContext={saved:SavedItem[];ready:boolean;error:string;save:(item:SavedItem)=>Promise<void>;isSaved:(key:string)=>boolean;play:(episode:any)=>void;watch:(type?:string)=>void;photo:(url:string,title:string)=>void;search:()=>void;journal:string;setJournal:(s:string)=>void;saveJournal:()=>Promise<boolean>;busy:boolean};
const Ctx=createContext<AppContext>(null!);
export const useCYI=()=>useContext(Ctx);
export const makeItem=(x:any,kind="Programme"):SavedItem=>({key:kind+":"+x.slug,title:x.title||x.name,href:x.href||"/branches?search="+encodeURIComponent(x.name),kind});
export function SaveButton({item,className="save-button"}:{item:SavedItem;className?:string}){const c=useCYI();const on=c.isSaved(item.key);return <button className={className+(on?" saved":"")} onClick={()=>c.save(item)} aria-label={(on?"Remove ":"Save ")+item.title} aria-pressed={on} disabled={c.busy}><Bookmark size={18} fill={on?"currentColor":"none"}/></button>}
function Brand(){return <Link href="/" className="brand" aria-label="CYI home"><img src={D.media.logo} alt="CYI"/><strong>CYI</strong><span>Christ for Youth International</span></Link>}
export function ButtonLink({href,children,variant="",external=false}:{href:string;children:ReactNode;variant?:string;external?:boolean}){return external?<a className={"btn "+variant} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={17}/></a>:<Link className={"btn "+variant} href={href}>{children}<ArrowRight size={17}/></Link>}
export function CTABand(){return <div className="wrap section"><div className="cta-band"><div><h2>There’s a place for you here.</h2><p>Come as you are. Grow with us. Make a difference.</p></div><ButtonLink href="/connect">Let’s connect</ButtonLink></div></div>}
export default function CYIShell({children}:{children:ReactNode}){
 const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>32);update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update);},[]);
 const location=useAppLocation();const pathname=location.split(/[?#]/)[0];const [menu,setMenu]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [q,setQ]=useState("");const [video,setVideo]=useState("");const [photo,setPhoto]=useState<{url:string;title:string}|null>(null);const [saved,setSaved]=useState<SavedItem[]>([]);const [ready,setReady]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [journal,setJournal]=useState("");const [episode,setEpisode]=useState<any>(null);const [playing,setPlaying]=useState(false);const [audioError,setAudioError]=useState(false);const audioRef=useRef<HTMLAudioElement>(null);
 useEffect(()=>{setMenu(false);setSearchOpen(false)},[location]);
 useEffect(()=>{const route=resolvePath(location);const record=allItems.find(x=>x.href?.split("?")[0]==="/"+route);document.title=route==="home"?"CYI | Alive with Purpose.":(record?.title||route.split("/").pop()?.replace(/-/g," ").replace(/\b\w/g,(x:string)=>x.toUpperCase()))+" | CYI"},[location]);
 useEffect(()=>{const hash=window.location.hash.slice(1);const target=pathname==="/environments"?D.programmes.find((x:any)=>x.slug===hash):pathname==="/resources"?D.resources.find((x:any)=>x.slug===(hash==="podcast"?"kingdom-move":hash)):null;if(target){window.history.replaceState({},"",target.href);window.dispatchEvent(new Event("cyi:navigate"))}},[location]);
 useEffect(()=>{const controller=new AbortController();fetch("/api/collection",{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error("Your collection is temporarily unavailable. Please try again later.");const x:any=await r.json();setSaved(x.saved);setJournal(x.journal||"");setReady(true)}).catch(e=>{if(e.name!=="AbortError")setError(e.message)});return()=>controller.abort()},[]);
 async function update(payload:any){setBusy(true);try{const r=await fetch("/api/collection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw Error(d.error||"Could not save. Please try again.");setSaved(d.saved);setError("");setReady(true);return true}catch(e){toast.error(e instanceof Error?e.message:"Could not save");return false}finally{setBusy(false)}}
 async function save(item:SavedItem){if(!ready){toast.error(error||"Your collection is loading. Please try again.");return}const exists=saved.some(x=>x.key===item.key);if(await update({action:exists?"remove":"save",item})){toast.success(exists?"Removed from My CYI":"Saved to My CYI")}}
 async function saveJournal(){const ok=await update({action:"journal",journal});if(ok)toast.success("Reflection saved");return ok}
 function play(e:any){setEpisode(e);setAudioError(false);setPlaying(true);setTimeout(()=>audioRef.current?.play().catch(()=>setPlaying(false)),80)}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==="k"){e.preventDefault();setSearchOpen(true)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:"search_cyi_content",title:"Search CYI",description:"Find CYI programmes, branches, devotionals and media; opens the same search results visible on the site.",inputSchema:{type:"object",properties:{query:{type:"string",maxLength:100}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:any){if(typeof input?.query!=="string"||input.query.length>100)throw Error("A query of up to 100 characters is required");setQ(input.query);setSearchOpen(true);return {results:allItems.filter(x=>(x.title+" "+(x.description||"")).toLowerCase().includes(input.query.toLowerCase())).slice(0,12).map(x=>({title:x.title,url:x.href,type:x.kind}))}}},{signal:lifecycle.signal})).catch(()=>{});}catch{};return()=>lifecycle.abort()},[]);
 const nav=[["Our story","/about"],["Experiences","/environments"],["Find a branch","/branches"],["Watch & listen","/resources"],["Explore CYI","/explore"]];
 const results=allItems.filter(x=>(x.title+" "+(x.description||"")+" "+(x.country||"")).toLowerCase().includes(q.toLowerCase())).slice(0,12);
 return <Ctx.Provider value={{saved,ready,error,save,isSaved:key=>saved.some(x=>x.key===key),play,watch:(type="vimeo")=>setVideo(type),photo:(url,title)=>setPhoto({url,title}),search:()=>setSearchOpen(true),journal,setJournal,saveJournal,busy}}>
 <a href="#main-content" className="skip">Skip to content</a>
 <div className="announcement"><span>A GENERATION ALIVE WITH PURPOSE.</span><Link href="/explore">Explore the CYI family <ArrowUpRight size={14}/></Link></div>
 <header className={"site-header"+(scrolled?" scrolled":"")}><div className="wrap nav-shell"><Brand/><nav className="nav-links" aria-label="Main navigation">{nav.map(([name,url])=><Link key={url} href={url} className={pathname.startsWith(url)?"active":""} aria-current={pathname.startsWith(url)?"page":undefined}>{name}</Link>)}</nav><div className="nav-actions"><button className="round" aria-label="Search CYI" onClick={()=>setSearchOpen(true)}><Search size={20}/></button><Link href="/my-cyi" className="round" aria-label="My CYI saved collection"><Bookmark size={20}/></Link><Link className="btn small" href="/connect">Get connected <ArrowUpRight size={16}/></Link><button className="round menu-toggle" aria-expanded={menu} aria-controls="mobile-menu" aria-label={menu?"Close menu":"Open menu"} onClick={()=>setMenu(!menu)}>{menu?<X size={21}/>:<Menu size={21}/>}</button></div></div>{menu&&<nav className="mobile-menu" id="mobile-menu" aria-label="Mobile navigation">{[...nav,["Community projects","/projects"],["Photo gallery","/gallery"],["My CYI","/my-cyi"],["Give & support","/give"],["Our leadership","/leadership"],["Our ministries","/ministries"],["Stories","/stories"],["Leadership application","/executive-leadership-application"],["Fellowship feedback","/opm-feedback"],["Get connected","/connect"]].map(([name,url])=><Link href={url} key={url} onClick={()=>setMenu(false)} className={pathname.startsWith(url)?"active":""}>{name}</Link>)}</nav>}</header>
 <main id="main-content" tabIndex={-1} className="page-enter" key={location}><ClientBoundary>{children}</ClientBoundary></main>
 <footer className="footer" id="footer"><div className="wrap"><div className="footer-top"><div><Brand/><p>Creating room for youth to serve.<br/>Growing in Christ. Reaching our generation.</p><div className="socials"><a href="https://www.instagram.com/connectcyi/" aria-label="CYI Instagram" target="_blank" rel="noreferrer"><Instagram size={21}/></a><a href="https://www.facebook.com/ConnectCYI/" aria-label="CYI Facebook" target="_blank" rel="noreferrer"><Facebook size={21}/></a><a href="https://twitter.com/thinkcyi" aria-label="CYI on X" target="_blank" rel="noreferrer">𝕏</a><a href="https://www.youtube.com/channel/UCuSiqOgiuJ7DG8op4FKbk2w" aria-label="CYI TV on YouTube" target="_blank" rel="noreferrer"><Play size={21}/></a></div></div><div><h4>Find your place</h4><div className="footer-links"><Link href="/about">Our story & values</Link><Link href="/branches">Find a branch</Link><Link href="/environments">Camps & experiences</Link><Link href="/programmes/one-way-missions">One Way Missions</Link><Link href="/ministries">Our ministries</Link><Link href="/projects">Community projects</Link><Link href="/leadership">Our leadership</Link><Link href="/executive-leadership-application">Leadership application</Link><Link href="/opm-feedback">Fellowship feedback</Link><Link href="/explore">Explore every page</Link></div></div><div><h4>Keep growing</h4><div className="footer-links"><Link href="/resources/kingdom-move">The Kingdom Move</Link><Link href="/resources/cyi-radio">CYI Radio</Link><Link href="/resources/cyi-tv">CYI TV</Link><Link href="/resources/cyi-blog">CYI Blog</Link><Link href="/precious-moments">Precious Moments</Link><Link href="/gallery">Life at CYI</Link></div></div><div><h4>Say hello</h4><p>{D.contact.address}</p><div className="footer-links" style={{marginTop:18}}><a href={D.contact.tel}>{D.contact.phone}</a><Link href="/connect">Get in touch <ArrowUpRight size={14} style={{display:"inline"}}/></Link><Link href="/give">Support the mission <Heart size={14} style={{display:"inline"}}/></Link></div></div></div><div className="footer-huge" aria-hidden="true">ALL FOR CHRIST.</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Christ for Youth International.</span><div className="row"><Link href="/privacy">Privacy & your data</Link><span>Faith. Friendship. Purpose.</span></div></div></div></footer>
 {episode&&<div className="audio-dock"><img src={D.media.podcast} alt="The Kingdom Move cover"/><div><small>THE KINGDOM MOVE</small><strong>{episode.title}</strong></div><audio ref={audioRef} src={episode.audioUrl} controls autoPlay preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setAudioError(true)}/>{audioError&&<a href={episode.link} target="_blank" rel="noreferrer">Open episode</a>}<button className="round" onClick={()=>setEpisode(null)} aria-label="Close audio player"><X size={19}/></button></div>}
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="dialog-wide"><DialogTitle className="dialog-title">What are you looking for?</DialogTitle><DialogDescription>Find your next camp, community, message or devotional.</DialogDescription><div className="searchbox"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} maxLength={100} placeholder="Search everything CYI…" aria-label="Search all CYI content"/></div><div className="search-dialog-results">{results.map(x=><Link href={x.href} key={x.kind+x.slug} onClick={()=>setSearchOpen(false)}><span>{x.title}<small>{x.kind}</small></span><ArrowUpRight size={18}/></Link>)}{!results.length&&<p style={{padding:25}}>No matches. Try “camp”, “Adenta” or “wisdom”.</p>}</div></DialogContent></Dialog>
 <Dialog open={!!video} onOpenChange={o=>{if(!o)setVideo("")}}><DialogContent className="dialog-wide"><DialogTitle className="dialog-title">{video==="youtube"?"CYI TV":"CYI — Together"}</DialogTitle><DialogDescription>From the Christ for Youth International video collection.</DialogDescription>{video&&<iframe className="video-frame" src={video==="youtube"?"https://www.youtube-nocookie.com/embed/-hAjrJOuzmM?autoplay=1":"https://player.vimeo.com/video/1210826257?autoplay=1&title=0&byline=0"} title="CYI video player" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/>}<a className="textlink" href={video==="youtube"?"https://www.youtube.com/watch?v=-hAjrJOuzmM":"https://vimeo.com/1210826257"} target="_blank" rel="noreferrer">Open on {video==="youtube"?"YouTube":"Vimeo"} <ExternalLink size={15}/></a></DialogContent></Dialog>
 <Dialog open={!!photo} onOpenChange={o=>{if(!o)setPhoto(null)}}><DialogContent className="dialog-wide"><DialogTitle className="dialog-title">{photo?.title}</DialogTitle><DialogDescription>Life together, through the CYI lens.</DialogDescription>{photo&&<img src={photo.url} alt={photo.title}/>}</DialogContent></Dialog><Toaster richColors position="bottom-right"/>
 </Ctx.Provider>;
}
