"use client";
import {useState} from "react";
import {ArrowUpRight,ArrowRight,ArrowDown,Play,MapPin,Headphones,BookOpen,Heart,Plus} from "lucide-react";
import Link from "./navigation";
import HeroFilm from "./hero-film";
import {D,useCYI,SaveButton,makeItem,ButtonLink} from "./cyi-shell";

const journeys=[
 {Icon:MapPin,no:"01",title:"Find your people",sub:"Your community is waiting.",href:"/branches",label:"BRANCHES"},
 {Icon:Heart,no:"02",title:"Make your move",sub:"Camps. Missions. Moments that matter.",href:"/environments",label:"EXPERIENCES"},
 {Icon:Headphones,no:"03",title:"Feed your faith",sub:"Something good for your headphones.",href:"/resources",label:"WATCH + LISTEN"},
 {Icon:BookOpen,no:"04",title:"Go a little deeper",sub:"A little stillness. A lot of possibility.",href:"/precious-moments",label:"READ + REFLECT"}
];
export default function HomeExperience(){
 const c=useCYI();const [rotate,setRotate]=useState(false);
 return <div className={"electric-home"+(!rotate?" motion-paused":"")}>
  <section className="cinematic-hero" aria-labelledby="electric-title">
   <HeroFilm onPlaybackChange={setRotate}/>
   <div className="cinematic-content wrap">
    <div className="cinematic-copy">
     <div className="electric-kicker">CHRIST FOR YOUTH INTERNATIONAL</div>
     <h1 id="electric-title">MADE FOR<br/><em>MORE.</em></h1>
     <p>A life of faith. A world of possibility.<br/>Find your people, discover your gifts, and become who God created you to be.</p>
     <div className="electric-actions"><ButtonLink href="/branches" variant="coral">Find my community</ButtonLink><Link href="/environments" className="cinematic-explore">Explore CYI <ArrowUpRight size={19}/></Link></div>
    </div>
   </div>
   <Link href="#your-next-step" className="cinematic-scroll"><ArrowDown size={18}/><span>YOUR NEXT CHAPTER STARTS HERE</span></Link>
  </section>
  <div className="electric-marquee" aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>FAITH WITH FEELING <b>✳</b> LIFE WITH PURPOSE <b>✳</b> PEOPLE WHO GET YOU <b>✳</b></span>)}</div></div>
  <section className="electric-paths wrap section" id="your-next-step"><div className="path-intro"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>THIS WAY<br/>TO <em>MORE.</em></h2><p>There’s more than one way to find your place. Start with what moves you.</p></div><div className="path-grid">{journeys.map(({Icon,no,title,sub,href,label})=><Link href={href} key={no} className={"electric-path path-"+no}><div className="path-label"><span>{label}</span><span>{no}</span></div><Icon className="path-icon" size={36} strokeWidth={1.4}/><div><h3>{title}</h3><p>{sub}</p></div><span className="path-arrow"><ArrowUpRight size={23}/></span></Link>)}</div></section>
  <section className="electric-manifesto"><div className="wrap manifesto-grid"><div className="manifesto-image"><img src={D.media.outreach} alt="CYI serving children in the community" loading="lazy"/><span className="manifesto-tag">LOVE IS A VERB. <Heart size={18}/></span><span className="manifesto-side">THE WORLD NEEDS WHAT YOU CARRY.</span></div><div className="manifesto-copy"><span className="eyebrow">A BIG FAITH. AN EVEN BIGGER FAMILY.</span><h2>WE’RE HERE<br/>FOR THE<br/><em>REAL THING.</em></h2><p>{D.mission}</p><Link href="/about" className="underlink">Meet the movement <ArrowUpRight/></Link><div className="manifesto-facts"><div><b>{D.branches.length}</b><small>Branch listings</small></div><div><b>10</b><small>CYI experiences</small></div><div><b>01</b><small>Shared purpose</small></div></div></div></div></section>
  <section className="electric-experiences section"><div className="wrap"><div className="editorial-heading"><div><span className="eyebrow">COLLECT MOMENTS. BECOME MORE.</span><h2>YOU HAD TO<br/><em>BE THERE.</em><span className="heading-orbit" aria-hidden="true">↗</span></h2></div><div><p>From campfire conversations to serving a whole community. This is faith you can feel.</p><ButtonLink href="/environments" variant="outline-dark">Explore all 10 experiences</ButtonLink></div></div><div className="electric-experience-grid">{[D.programmes[4],D.programmes[5],D.programmes[6]].map((p:any,i:number)=><article className={"electric-experience experience-"+i} key={p.slug}><Link href={p.href} className="experience-photo"><img src={p.image} alt={p.title} loading="lazy"/><span className="experience-number">0{i+1}</span><span className="experience-category">{p.category}</span></Link><div className="experience-info"><Link href={p.href}><h3>{p.title}</h3><p>{p.summary}</p><span className="experience-open">Discover the experience <ArrowUpRight size={20}/></span></Link><SaveButton item={makeItem(p)}/></div></article>)}</div><div className="experience-caption"><span>FIVE CAMPS. WORSHIP. MISSIONS. PRAYER. FAMILY.</span><Link href="/environments" className="underlink">Which one is your next chapter? <ArrowRight size={19}/></Link></div></div></section>
  <section className="electric-frequency section"><div className="wrap"><div className="editorial-heading"><div><span className="eyebrow"><span className="live-dot"/> GOOD NEWS. GOOD FREQUENCY.</span><h2>FAITH. WITH<br/>THE <em>VOLUME UP.</em></h2></div><Link href="/resources" className="underlink">Enter the media room <ArrowUpRight/></Link></div><div className="frequency-player"><div className="frequency-art"><img src={D.media.podcast} alt="The Kingdom Move with Roderick Agyekum" loading="lazy"/><button onClick={()=>c.play(D.episodes[0])} aria-label="Play the latest Kingdom Move episode"><Play size={34} fill="currentColor"/></button><span className="frequency-stamp">PRESS PLAY.<br/>CARRY PURPOSE.</span></div><div className="frequency-copy"><span className="eyebrow">THE KINGDOM MOVE PODCAST</span><h3>{D.episodes[0].title}</h3><p>{D.episodes[0].description}</p><div className="row"><button className="btn coral" onClick={()=>c.play(D.episodes[0])}><Play size={18} fill="currentColor"/> Listen now</button><span className="episode-duration">{D.episodes[0].duration.replace(/^00:/,"")} · AUDIO</span></div><div className="frequency-wave" aria-hidden="true">{Array.from({length:54},(_,i)=><i key={i} style={{height:12+((i*17+i*i*3)%39)}}/>)}</div><div className="editorial-episodes">{D.episodes.slice(1,4).map((e:any,i:number)=><button key={e.slug} onClick={()=>c.play(e)}><span>0{i+2}</span><div><strong>{e.title}</strong><small>{e.duration.replace(/^00:/,"")} · The Kingdom Move</small></div><Play size={20}/></button>)}</div></div></div><div className="electric-channels">{[["01","CYI TV","Stories in motion.","/resources/cyi-tv"],["02","CYI RADIO","Stay on the frequency.","/resources/cyi-radio"],["03","CYI BLOG","A fresh perspective.","/resources/cyi-blog"],["04","PRECIOUS MOMENTS","Make room to reflect.","/precious-moments"]].map(([n,title,desc,href])=><Link key={n} href={href}><small>{n}</small><h3>{title}</h3><p>{desc}</p><ArrowUpRight size={25}/></Link>)}</div></div></section>
  <section className="electric-giving wrap section"><div className="giving-message"><span className="eyebrow">SEPTEMBER 2026 · GENEROSITY</span><h2>GOOD THINGS<br/>ARE BETTER<br/><em>SHARED.</em></h2><p>Our shared focus is generosity. More love. More room. More to give. Make space to read, reflect, and turn what you believe into something you do.</p><div className="row"><ButtonLink href="/precious-moments">Read & reflect</ButtonLink><Link href="/give" className="underlink">Give with purpose <ArrowUpRight size={20}/></Link></div></div><div className="giving-art"><span className="giving-doodle" aria-hidden="true">♡</span><button onClick={()=>c.photo(D.home.themeImage,"September 2026 — Generosity")}><img src={D.home.themeImage} alt="Original CYI September 2026 Generosity artwork" loading="lazy"/><span>THE HEARTBEAT THIS MONTH <Plus size={20}/></span></button><span className="giving-note">A little kindness.<br/>An extraordinary ripple.</span></div></section>
  <section className="electric-voices section"><div className="wrap"><div className="editorial-heading"><div><span className="eyebrow">REAL PEOPLE. LIFE-CHANGING CONNECTIONS.</span><h2>MY PEOPLE.<br/><em>MY CYI.</em></h2></div><Link href="/stories" className="underlink">More from the family <ArrowUpRight/></Link></div><div className="electric-voice-grid">{D.testimonials.slice(0,3).map((t:any,i:number)=><article key={t.name}><div className="voice-count">0{i+1} / THE FAMILY <span>“</span></div><blockquote>{t.quote}</blockquote><div className="voice-person"><img src={t.image} alt={t.name} loading="lazy"/><div><h3>{t.name}</h3><span>{t.location}</span></div><Heart size={22}/></div></article>)}</div></div></section>
  <section className="electric-life section"><div className="wrap"><div className="editorial-heading"><div><span className="eyebrow">THE MOMENTS BETWEEN THE MOMENTS.</span><h2>UNFILTERED.<br/><em>UNFORGETTABLE.</em></h2></div><Link href="/gallery" className="underlink">Open the photo journal <ArrowUpRight/></Link></div></div><div className="electric-filmstrip">{[D.media.family,D.media.worship,D.media.hero,D.media.community].map((im:string,i:number)=><button key={im} onClick={()=>c.photo(im,["The CYI family","Worship together","Gifts in motion","Serving our community"][i])}><img src={im} alt={["Friends at CYI","CYI worship gathering","CYI creative performance","CYI volunteers together"][i]} loading="lazy"/><span>{["BELONG.","BELIEVE.","BECOME.","BE THE DIFFERENCE."][i]} <Plus size={20}/></span></button>)}</div></section>
  <section className="electric-invitation"><img src="/media/cyi-electric-ribbon.webp" alt="" loading="lazy"/><div className="wrap"><span className="eyebrow">YOU + US + A LITTLE FAITH.</span><h2>YOUR NEXT<br/>CHAPTER?<br/><em>IT STARTS HERE.</em></h2><ButtonLink href="/connect" variant="coral">I’m ready. Let’s connect.</ButtonLink><span className="invitation-hand" aria-hidden="true">↗</span></div></section>
 </div>
}
