import {notFound,redirect} from "next/navigation";
import {siteMetadata} from "@/lib/site-metadata";
import CYIApp from "../cyi-app";
import data from "../content.json";
import additional from "../additional-pages.json";
const routes=["explore","archive","archive/family-games",...additional.filter(p=>p.slug!=="family-games").map(p=>p.slug),...data.branches.map(p=>"branches/"+p.slug),"projects",...data.projects.map(x=>"projects/"+x.slug),"about","environments","branches","resources","precious-moments","leadership","gallery","stories","connect","my-cyi","ministries","give","privacy",...data.programmes.map(x=>"programmes/"+x.slug),...data.resources.map(x=>"resources/"+x.slug),...data.devotionals.map(x=>"devotionals/"+x.slug)];
export function generateStaticParams(){return [...new Set(routes)].map(route=>({slug:route.split("/")}));}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const route=slug.join('/');const record=[...data.projects,...data.programmes,...data.resources,...data.devotionals,...additional,...data.branches.map(b=>({...b,title:"CYI "+b.name}))].find(x=>route===x.slug||route.endsWith('/'+x.slug));const title=record?.title||route.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());return siteMetadata(title,"/"+route);}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const route=slug.join('/');const aliases:Record<string,string>={"my-cyi-story":"/stories","family-games":"/programmes/family-games","savedtoserve":"/programmes/saved-2-serve"};if(aliases[route])redirect(aliases[route]);const oldArticle=data.devotionals.find(x=>x.slug===route);if(oldArticle)redirect("/devotionals/"+route);const oldProject=data.projects.find(x=>x.slug===route);if(oldProject)redirect("/projects/"+route);if(!routes.includes(route))notFound();return <CYIApp route={route}/>;}
